name: Validate YAML

 

on:

 deploy:

 

jobs:

  validate-yaml:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Validate YAML file

        run: yamllint my-file.yml
